#!/bin/bash

# submit the next five items in the queue to aicrowd and capture results
# stop on error and report 
# aicrowd limits five scorings per day

# cd to queue dir
cd $1

# optionally limit how many items to submit
# useful for ad hoc runs and testing
COUNT=${2:-5}

for submission in `ls -tr | head -n ${COUNT}`
do
  DATESTR=`date +'%Y-%m-%d-%H:%M:%S'`
  LOGFILE=submits/${submission}-${DATESTR}.log
  CMD="aicrowd submission create -c spotify-million-playlist-dataset-challenge \
                            -d ${submission} \
                            -f ${submission}"
  echo $CMD > $LOGFILE
  echo =============== >> $LOGFILE
  $CMD &>> $LOGFILE

  rcode=$?

  if [ $rcode -ne 0 ]
  then
    echo =========================
    echo aicrowd submission failed
    echo result code: $rcode
    echo =========================
    echo
    cat $LOGFILE
    exit $rcode
  else
    # remove the symlink to delete submission request from queue
    rm ${submission}
  fi

  # rest five min to avoid failures due to submit overload of aicrowd
  sleep 300

done

# everything succeeded so exit normally
exit 0
