#!/bin/bash

# submit the next five items in the queue to aicrowd and capture results
# stop on error and report 
# aicrowd limits five scorings per day

# cd to queue dir
cd $1

# optionally limit how many items to submit
# useful for ad hoc runs and testing
COUNT=${2:-5}

for submission in `ls -tr | head -n ${COUNT}`
do
  DATESTR=`date +'%Y-%m-%d-%H:%M:%S'`
  LOGFILE=submits/${submission}-${DATESTR}.log
  CMD="aicrowd submission create -c spotify-million-playlist-dataset-challenge \
                            -d ${submission} \
                            -f ${submission}"
  echo =============== >> $LOGFILE
  echo $CMD > $LOGFILE
  while ! $CMD &>> $LOGFILE
  do

    echo =========================
    echo aicrowd submission failed
    echo =========================
    echo

    # see it's a submit time limit and wait if so
    submittime=`awk '/Submission limit reached.*reset at/{print $11" "$12" "$13}' $LOGFILE`
    if [ "$submittime" == "" ]
    then
      cat $LOGFILE
      exit $rcode
    else
      echo Waiting for submit limit expiration: $submittime | tee -a $LOGFILE
      # sleep seconds until submit time
      # https://stackoverflow.com/a/646008/8928529
      current_epoch=$(date +%s)
      target_epoch=$(date -d "$submittime" +%s)

      sleep_seconds=$(( $target_epoch - $current_epoch ))

      echo sleep $sleep_seconds >> $LOGFILE
      sleep $sleep_seconds
    fi
  done

  # remove the symlink to delete submission request from queue on success
  rm ${submission}

  # rest five min to avoid failures due to submit overload of aicrowd
  sleep 300

done

# everything succeeded so exit normally
exit 0
