#!/bin/bash

# submit the next five items in the queue to aicrowd and capture results
# stop on error and report 
# aicrowd limits five scorings per day

# cd to queue dir
cd $1

for submission in `ls -tr | head -n 5`
do
  aicrowd submission create -c spotify-million-playlist-dataset-challenge \
                            -d ${submission} \
                            -f ${submission} > submits/${submission}.log
  rcode=$?

  if [ $rcode -ne 0 ]
  then
    echo =========================
    echo aicrowd submission failed
    echo result code: $rcode
    echo =========================
    echo
    cat submits/${submission}.log
    exit 1
  else
    # remove the symlink to delete submission request from queue
    rm ${submission}
  fi

  # rest five min to avoid failures due to submit overload of aicrowd
  sleep 300

done

# everything succeeded so exit normally
exit 0
